app/models.py
from . import db 
from . import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash




@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users' #Allows us ggive table a name of our choices
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    firstname = db.Column(db.String(255))
    lastname = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitches',backref = 'user',lazy = "dynamic")


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute on this object')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):    # makes it easier to debug our application
        return f'User {self.username}'

   


class Pitches(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    pitches = db.Column(db.String(2555))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comment = db.relationship('Comments',backref = 'pitch',lazy = "dynamic")


    # users = db.relationship('User',backref = 'role',lazy="dynamic")

    def save_pitches(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, id):
        pitches= Pitches.query.filter_by(id=id).all()
        return pitches

    def __repr__(self):
        return f'User {self.name}'


class Comments(db.Model):
    __tablename__ ='comments'
    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String(255))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))


    def save_comments(self):
        db.session.add(self)
        db.session.commit()



# python3.8 manage.py db init
# python3.8 manage.py db migrate -m "Initial Migration"
# python3.8 manage.py db upgrade

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField,StringField, TextAreaField,SelectField
from wtforms.validators import DataRequired
from ..models import User

class UpdateProfile(FlaskForm):
    fullname = StringField('FullName.',validators = [DataRequired()])

    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')


class PitchForm(FlaskForm):
    title = StringField('Pitch Title.',validators = [DataRequired()])
    category = SelectField(u'Select Pitch Category', choices=[('....Select Category', 'Select Category.....'), ('Technology', 'Technology'), ('Business', 'Business'), ('Health', 'Health')])
    pitches = TextAreaField('Your Pitch .',validators = [DataRequired()])

    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Leave us a comment about the pitch',validators = [DataRequired()])
    # postedby= StringField('Pitch Title.',validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
import os
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)

'''create app function'''
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    # configure UploadSet
    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

   

    return app

app/main/__init__.py
from flask import Blueprint
main= Blueprint('main', __name__)
from . import views ,errors

app/main/views.py
from flask import redirect, render_template, request, url_for,abort
from flask_login import login_required, current_user
from . import main
from ..models import Pitches, User,Comments
from .forms import PitchForm, UpdateProfile, CommentForm
from .. import db,photos

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Pitch Area. Where you pitch your ideas and get voted for'
    return render_template('index.html', title=title)


@main.route('/home',methods = ['GET','POST'])
@login_required
def home():
    pitches= Pitches.query.all()
    comments= Comments.query.all()
    return render_template('home.html', pitches=pitches, comments=comments)

@main.route('/view/',methods = ['GET','POST'])
@login_required
def view():
    comments= Comments.query.all()
    return render_template('view.html', comments=comments)


# @main.route('/categories/')
# def categories():
#     return render_template('categories.html')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    pitch = Pitches.query.filter_by(id=user.id).all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, pitch=pitch)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)



##....
@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        category = form.category.data
        pitches = form.pitches.data

        # Updating 
        new_pitch = Pitches(title=title,category=category,pitches=pitches,user=current_user)

        # save review method
        new_pitch.save_pitches()
        return redirect(url_for('.home'))

    return render_template('pitch.html',form=form)


@main.route('/comment/', methods=['GET','POST'])
@login_required
def comment():
    form= CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment)

        new_comment.save_comments()
        return redirect(url_for('.home'))

    return render_template('comment.html', form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{title}}</title>
</head>
<body>

    
</body>
</html> -->
{% extends 'bootstrap/base.html'%}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}


{% block content %} 

{% endblock %}

app/templates/categories.html
<p>lorem ipsum dolor sit amet, consectet</p>

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container"> 
    <div class="row">
      {{wtf.quick_form(form)}}
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>


{% endblock%}

app/templates/home.html
{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
    
{% endblock %}

{% block content %} 

<div class="container text-center ">
    Welcome {{current_user.username}}.
    <h3>Checkout the Pitches</h3>
    <a href="/pitch/" class="pitch p-4"><input type="button" value="Add A New Pitch"></a>

    <div class="container">
        <div class="row">
            {% for pitch in pitches %}
            <div class="col-md-4 card">
                    <div class="thumbnail">
                       
                        <h1>{{pitch.category}}</h1>
                        <h2>Title:{{pitch.title}}</h2>
                        <p>{{pitch.pitches}}</p>
                        <a href="/comment/"><input type="button" value="Comment"></a> 
                        <a href="/view/"><input type="button" value="View Comment"></a> 

    
                        
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

{% endblock %}


{% block content %}  
<div class="row container ">
    <div class=" main col-md-6">
        <h2>Welcome to Eazy Pitch. Where you do your pitch in Sixty seconds!</h2>
        <h2>The pitch categories available include:</h2>
        <ul>
            <p>Technlolgy</p>
            <p>Business</p>
            <p>Health</p>
            <p>Marketing</p>
        </ul>
    </div>
    <div class="col-md-5">
        <img src="../static/IMAGES/pitch.jpg" alt="">
        <p>Do you have an idea and don't know where to pitch it? We are here to sort you.</p>
        <a href="/pitch"><input type="button" value="ADD A PITCH"></a>


        
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar bg-danger" role="navigation">
    <div class="container-fluid">


        <a class="navbar-brand" href="/"> Eazy Pitch </a>
        {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="/home">Pitches</a>
        {%endif%}
        <!-- <a class="navbar-brand" href="">Home</a> -->
        <!-- <a class="navbar-brand" href="/categories/">Categories</a> -->


        <ul class="nav navbar-nav navbar-right navbar-brand">
            {% if current_user.is_authenticated %}
            <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
            <!-- <a href="/categories/">Categories</a> -->

            <!-- <a style="color:orangered;padding:15px;">{{current_user.username}}</a> -->
            <a href="{{url_for('auth.logout')}}">Sign out</a>

            {% else %}
            <a href="{{url_for('auth.login')}}">Sign in</a>
            {%endif%}
        </ul>





    </div>
</div>

app/templates/not_found.html
<h1>OOps wrong Entry. Please check the url</h1>

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
{% endblock %}

{% block content %}
<div class="container"> 
    <div class="row">
      {{wtf.quick_form(form)}}
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-4">
      <h3> {{user.username| capitalize}} </h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <p> {{user.bio}}</p>
      {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
      {% endif %}
      {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Add Bio</a>
    {% endif %}
    
    </div>
   

    <!--Display profile photo-->
    <div class="col-md-4">

      {% if user.profile_pic_path %}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
      {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
    </div>
  </div>
  {% for pitc in pitch %}
  <h1>{{pitc.category}}</h1>
  <h2>{{pitc.title}}</h2>
  <p>{{pitc.pitches}}</p>
  <a href="/comment/"><input type="button" value="Add A Comment"></a>
  <a href="/view/"><input type="button" value="View Comment"></a>

  {% endfor %}
  
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>

<a href="/home">Back</a>
{% endblock %}

app/templates/view.html
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
    <link rel="stylesheet" href="../static/css/home.css">
</head>

<body>
    
    
</body>

</html> -->

{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

{% endblock %}

{% block content %}

<div class="container ">
    <h1 class="text-center">Comments</h1>
</div>
<div class="container">
    <div class="row">
        {% for comment in comments %}
        <div class="col-md-5 m-3 card">
                <div class="thumbnail">
                    <p>{{comment.comment}} Commented by: {{comment.postedby}}</p>   
                </div>
            </div>
        {% endfor %}
    </div>
    
</div>

{%endblock%}